### ISSUE TITLE
Package should have date field which stores date added to crantastic

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#26]
Now that we are regularly pulling in packages from CRAN, we really should have a package field that records the date that the was added to CRAN, and we should use this in preference to the date field in the package description.  (People often forget to update that field on release and it can be years out of date)

**Comment by bmaland** [comment]
The created_at field in the Version table probably solves this issue

**Comment by hadley** [comment]
In that case, we just need a good algorithm for which to use.  Maybe if created_at > 22 June 2009, use created_at, otherwise use date?  Or maybe we should have a separate field displaying when the package was added to crantastic.

**Comment by bmaland** [comment]
Maybe we should ditch the Date field and instead use Date/Publication ? As far as I can tell, that field is autogenerated when published to CRAN. Using created_at could fail and produce incorrect dates if e.g. the cron task stops running for a day

**Comment by hadley** [comment]
I did not know that field existed.  It sounds perfect.

**Comment by bmaland** [comment]
Unfortunately, this field is not included in packages on Bioconductor. One option is to prefer the Date/Publication field, and then fall back on the Packaged field if its not available. Packaged is set to the date the developer builds the package on his machine, so it should be fairly accurate.

**Comment by hadley** [comment]
That sounds reasonable to me.

**Comment by bmaland** [comment]
This is now implemented. Another nice thing is that these fields also include time of day, instead of just the date.

Note that the timelines still use created_at for all the entries. I think this makes most sense since it reflects when things got updated on Crantastic and not necessarily when the packages reached CRAN. (It would be trivial to use the "date" attribute instead of created_at for packages and versions though, if you'd prefer that)

**Comment by hadley** [comment]
Sounds good.
