### ISSUE TITLE
Clarify licensing of user contributed material

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#47]
Some CC license?

**Comment by bmaland** [comment]
Maybe the same license that identi.ca uses? Creative Commons Attribution 3.0 license: http://creativecommons.org/licenses/by/3.0/ . We should then have some sort of agreement of terms displayed in the signup form (again, identi.ca can be used as the model).

I guess we should also place the site source code under an explicit license. Maybe MIT (makes things very simple since Rails and pretty much every plugin is MIT-licensed)?

**Comment by hadley** [comment]
I think we should be a little more restrictive than that - how about http://creativecommons.org/licenses/by-sa/3.0/ ?

And MIT license for the source sound perfect.

**Comment by bmaland** [comment]
Share Alike looks good. Would it be enough to add a link with some brief info in the footer, and a terms of agreement that has to be accepted for new signups?

I'll add a LICENSE file to the source repository and mention it in the Readme.

**Comment by hadley** [comment]
Yeah, that sounds fine.

**Comment by bmaland** [comment]
Pretty much done now, unless the wording needs adjustments. However, users signing up with RPX currently skips over the agreement checkbox. I'll fix that later

**Comment by bmaland** [comment]
hadley@aa50198f728e9b5b66eed3d4ea122f1392fcda59 makes sure that everyone accepts the TOS
